export const initialProducts = [
  {
    id: "p1",
    title: "HP Pavilion Intel Core i5 13th Gen - (16 GB/512 GB SSD/Windows 11 Home) Thin and Light Laptop",
    category: "Gadgets",
    price: 52990,
    originalPrice: 77990,
    colors: ["Natural Silver", "Warm Gold"],
    rating: 4.4,
    ratingCount: 842,
    image: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&q=80&w=600",
    description: "Experience premium performance with the HP Pavilion Laptop. Powered by an Intel Core i5 13th Gen processor, it delivers seamless multitasking and speed. Features a thin, lightweight design, backlit keyboard, and micro-edge Full HD display.",
    stock: 8
  },
  {
    id: "p2",
    title: "Samsung Galaxy S24 5G (Onyx Black, 256 GB) (8 GB RAM)",
    category: "Gadgets",
    price: 74999,
    originalPrice: 89999,
    colors: ["Onyx Black", "Marble Gray", "Amber Yellow"],
    rating: 4.6,
    ratingCount: 3150,
    image: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&q=80&w=600",
    description: "Welcome to the era of mobile AI. With Galaxy S24 in your hands, you can unleash whole new levels of creativity, productivity and possibility starting with the most important device in your life. Your smartphone. Complete with 50MP camera and pro-grade nightography.",
    stock: 12
  },
  {
    id: "p3",
    title: "Nike Air Max Impact 4 Basketball Shoes For Men",
    category: "Fashion",
    price: 5945,
    originalPrice: 8495,
    colors: ["Black/White", "Grey/Red", "All White"],
    rating: 4.2,
    ratingCount: 420,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=600",
    description: "Elevate your game and your style. The Nike Air Max Impact 4 features Max Air cushioning in the heel to help absorb impact. Lightweight mesh upper keeps your feet cool, while the aggressive traction pattern helps you cut and pivot with confidence.",
    stock: 15
  },
  {
    id: "p4",
    title: "Puma Classic Solid Men Round Neck Green T-Shirt",
    category: "Fashion",
    price: 899,
    originalPrice: 1799,
    colors: ["Forest Green", "Classic Black", "Navy Blue"],
    rating: 4.1,
    ratingCount: 1520,
    image: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&q=80&w=600",
    description: "A comfortable, standard-fit t-shirt crafted from 100% premium cotton. Features the classic Puma cat logo on the chest. Perfect for daily casual wear or athletic training.",
    stock: 25
  },
  {
    id: "p5",
    title: "Wipro Vesta 4 Slice Automatic Grill Toaster & Maker",
    category: "Watch",
    price: 1899,
    originalPrice: 3299,
    colors: ["Midnight Black", "Steel Silver"],
    rating: 4.3,
    ratingCount: 685,
    image: "https://images.unsplash.com/photo-1583696959824-4d142d41f974?auto=format&fit=crop&q=80&w=600",
    description: "Make delicious, crispy grilled sandwiches in minutes with the Wipro Vesta Grill toaster. Features non-stick coating plates, cool-touch handle, oil collector tray, and auto shut-off technology for safety and ease.",
    stock: 6
  },
  {
    id: "p6",
    title: "Stylon Premium Fabric 3 Seater Sofa for Living Room",
    category: "Watch",
    price: 15999,
    originalPrice: 29999,
    colors: ["Royal Blue", "Charcoal Grey", "Beige"],
    rating: 4.5,
    ratingCount: 182,
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=600",
    description: "Add a touch of modern elegance to your living space. Handcrafted with high-density foam, durable fabric upholstery, and a sturdy solid wood frame, this sofa offers superior support and long-lasting durability.",
    stock: 4
  },
  {
    id: "p7",
    title: "Philips OneBlade Hybrid Trimmer & Shaver for Men",
    category: "Shoes",
    price: 1999,
    originalPrice: 2499,
    colors: ["Lime Green/Grey"],
    rating: 4.4,
    ratingCount: 4230,
    image: "https://images.unsplash.com/photo-1621607512214-68297480165e?auto=format&fit=crop&q=80&w=600",
    description: "Trim, edge, and shave any length of hair. The unique Philips OneBlade technology integrates a fast-moving cutter with a dual protection system, giving you an efficient and comfortable shave on longer hairs without irritating the skin.",
    stock: 20
  },
  {
    id: "p8",
    title: "L'Oreal Paris Revitalift 1.5% Pure Hyaluronic Acid Face Serum",
    category: "Shoes",
    price: 699,
    originalPrice: 999,
    colors: ["Clear"],
    rating: 4.3,
    ratingCount: 1120,
    image: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&q=80&w=600",
    description: "Intensely hydrating serum for plump, youthful, and radiant skin. Formulated with 1.5% Pure Hyaluronic Acid, it absorbs quickly with a non-sticky finish to immediately hydrate and reduce fine lines over time.",
    stock: 30
  }
];
